### ISSUE TITLE
Slicing amr_field not working if sliced region is too thin

### ISSUE THREAD

**Issue by jimgreen** [KristoforMaynard/Viscid#16]
For example, if the sliced region is within a cell's extension. I think this comes from `sliceutils.to_slice`. Is this intentioned so that a user should make sure the slice requested is reasonable?

This perhaps impacts non-amr fields, too.

**Comment by jimgreen** [comment]
I think slicing also fails when one patch has only one cell in the sliced region, because `fld = fld.slice_reduce(selection)` in `vpyplot.py:plot` will reduce its dimension by one silently.

**Comment by KristoforMaynard** [comment]
The issue is unclear... maybe some examples that don't work as expected, and how they should be expected to work.

**Comment by KristoforMaynard** [comment]
Reproducible with

```
    import viscid
    f = viscid.load_file(viscid.sample_dir + '/vpic_sample/*.vpc')
    f['bx']['x=:32.01'].data
```

The solution is to have `AMRField.slice(...)` and `AMRField.slice_reduce(...)` go through and make sure that all all the results have the same dimensions. It's important to maintain the semantics that `Field.slice(...)` reduces / keeps dimensions the same way ndarrays do.
